### ISSUE TITLE
`subAffixList`里的`step`是什么意思？

### ISSUE THREAD

**Issue by KyleRicardo** [Mar-7th/March7th-Docs#1]
```jsonc
{
  "affixId": 2,
  // Base value count
  "cnt": 1,
  // Boost value count
  "step": 1
}
```
根据我的理解，`cnt`表示这个词条的个数，但是`step`是什么意思呢？求解。

**Comment by mobyw** [comment]
遗器的副词条数值由基础值和提升值决定，单个副词条的数值范围在基础值（最低）和基础值加上两倍提升值（最高）之间。

**Comment by KyleRicardo** [comment]
非常感谢解答。我参考了一下大佬的这个https://github.com/Mar-7th/StarRailRes/blob/master/index_new/cn/relic_sub_affixes.json

发现提升值约为基础值的1/8。另外参考了一下enka的算法，貌似是将最大值作为1，所以最小值和中等值分别算作0.8和0.9个词条。

**Comment by mobyw** [comment]
具体的数值配置应保持从配置文件中取得，非明确的规则随时可能会被打破
