### ISSUE TITLE
API 文档：MemoryInfo 的 chaosId 与 chaosLevel 应该设为 Optional。

### ISSUE THREAD

**Issue by ShikiSuen** [Mar-7th/March7th-Docs#2]
如题。
测试用UID：114514810。

**Comment by ShikiSuen** [comment]
按理来讲最终使用者应该将 MemoryInfo 彻底不实作的。
但给出的 Python Example 里面的 chaosId 与 chaosLevel 不是 Optional。
这在某些语言当中会让整个 JSONDecoder 在解码时直接罢工（点名 Swift）。

所以官方 API 的范例应该将这两个变数设为 Optional。

**Comment by ShikiSuen** [comment]
刚刚检查了仓库发现该问题早就解决了。
剩下的问题是这个网站为什么会有残留： https://march7th.xiaohei.moe/zh/resource/mihomo_api.html#mihomo-parsedapi-%E8%BF%94%E5%9B%9E%E5%AD%97%E6%AE%B5

我先关掉 issue。

**Comment by mobyw** [comment]
可以参考 Python 库中的源代码 https://github.com/Mar-7th/mihomo.py/blob/master/mihomo/model.py

文档此部分还未更新
